"""Build RIME table dictionaries for English and Swedish from frequency lists.

  data/en_50k.txt -> ../rime/en_words.dict.yaml   (code = word, text = word)
  data/sv_50k.txt -> ../rime/sv_words.dict.yaml   (code = ascii-folded, text = real spelling)
Also writes ../rime/lua/langid_words.lua with the two word sets so the filter
can tell which dictionary a candidate came from.
"""
from __future__ import annotations

import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
DATA = HERE / "data"
RIME = HERE.parent / "rime"

FOLD = str.maketrans({"å": "a", "ä": "a", "ö": "o", "é": "e", "ü": "u"})
EN_LIMIT = 40000
SV_LIMIT = 40000


def read_freq(path: Path):
    for line in path.read_text(encoding="utf-8", errors="ignore").splitlines():
        parts = line.strip().split()
        if len(parts) == 2:
            yield parts[0], int(parts[1])


def build(name: str, src: Path, limit: int, fold: bool):
    entries = []
    seen = set()
    for w, c in read_freq(src):
        lw = w.lower()
        if not re.fullmatch(r"[a-zåäöéü]+", lw) or len(lw) < 2 and lw not in ("a", "i", "å", "ö"):
            continue
        if lw in seen:
            continue
        seen.add(lw)
        code = lw.translate(FOLD) if fold else lw
        entries.append((lw, code, c))
        if len(entries) >= limit:
            break
    header = f"""# generated by build_dicts.py
---
name: {name}
version: "1"
sort: by_weight
...
"""
    body = "\n".join(f"{t}\t{code}\t{c}" for t, code, c in entries)
    (RIME / f"{name}.dict.yaml").write_text(header + body + "\n", encoding="utf-8")
    print(name, len(entries), "entries")
    return [t for t, _, _ in entries]


def lua_set(name: str, words):
    esc = lambda s: s.replace("\\", "\\\\").replace('"', '\\"')
    return f"M.{name} = {{\n" + "".join(f'["{esc(w)}"]=1,' + ("\n" if i % 20 == 19 else "") for i, w in enumerate(words)) + "\n}\n"


if __name__ == "__main__":
    RIME.mkdir(exist_ok=True)
    (RIME / "lua").mkdir(exist_ok=True)
    en = build("en_words", DATA / "en_50k.txt", EN_LIMIT, fold=False)
    sv = build("sv_words", DATA / "sv_50k.txt", SV_LIMIT, fold=True)
    lua = "-- generated by build_dicts.py\nlocal M = {}\n" + lua_set("en", en) + lua_set("sv", sv) + "return M\n"
    (RIME / "lua" / "langid_words.lua").write_text(lua, encoding="utf-8")
    print("wrote langid_words.lua")
